"""
ROI Distribution Comparison & Quality Control Verification CLI Tool
Compares forward annualized ROI (CAGR) distribution generated by the Investment Thesis Agent
against empirical historical distributions (CRSP / Hendrik Bessembinder, J.P. Morgan Asset Management, S&P Dow Jones).

Conforms to:
- context/schemas/investment_thesis_schema.json
- context/schemas/return_engine_schema.json
- AGENTS.md (No emojis, no standalone horizontal rules, 20-year hurdle standard)
"""

import argparse
import json
import math
import os
import sys
from typing import Dict, Any, List, Tuple


def calculate_percentile(sorted_data: List[float], percentile: float) -> float:
    """Calculates percentile from a sorted list of floats using linear interpolation."""
    if not sorted_data:
        return 0.0
    k = (len(sorted_data) - 1) * (percentile / 100.0)
    f = math.floor(k)
    c = math.ceil(k)
    if f == c:
        return sorted_data[int(k)]
    d0 = sorted_data[int(f)] * (c - k)
    d1 = sorted_data[int(c)] * (k - f)
    return round(d0 + d1, 2)


def compute_distribution_statistics(values: List[float]) -> Dict[str, float]:
    """Computes standard sample distribution statistics."""
    if not values:
        return {}
    sorted_vals = sorted(values)
    n = len(sorted_vals)
    mean_val = sum(sorted_vals) / n
    variance = sum((x - mean_val) ** 2 for x in sorted_vals) / (n - 1 if n > 1 else 1)
    std_dev = math.sqrt(variance)

    # Skewness
    if std_dev > 0 and n > 2:
        m3 = sum((x - mean_val) ** 3 for x in sorted_vals) / n
        skewness = m3 / (std_dev ** 3)
    else:
        skewness = 0.0

    # Kurtosis (excess)
    if std_dev > 0 and n > 3:
        m4 = sum((x - mean_val) ** 4 for x in sorted_vals) / n
        kurtosis = (m4 / (std_dev ** 4)) - 3.0
    else:
        kurtosis = 0.0

    neg_count = sum(1 for x in sorted_vals if x < 0)
    high_cagr_count = sum(1 for x in sorted_vals if x >= 20.0)
    tbill_count = sum(1 for x in sorted_vals if x < 4.5)

    return {
        "count": n,
        "min_pct": round(sorted_vals[0], 2),
        "p5_pct": calculate_percentile(sorted_vals, 5.0),
        "p10_pct": calculate_percentile(sorted_vals, 10.0),
        "p25_pct": calculate_percentile(sorted_vals, 25.0),
        "p50_median_pct": calculate_percentile(sorted_vals, 50.0),
        "p75_pct": calculate_percentile(sorted_vals, 75.0),
        "p90_pct": calculate_percentile(sorted_vals, 90.0),
        "p95_pct": calculate_percentile(sorted_vals, 95.0),
        "max_pct": round(sorted_vals[-1], 2),
        "mean_pct": round(mean_val, 2),
        "std_dev_pct": round(std_dev, 2),
        "skewness": round(skewness, 2),
        "kurtosis": round(kurtosis, 2),
        "pct_negative_return": round((neg_count / n) * 100.0, 1),
        "pct_exceeding_20_cagr": round((high_cagr_count / n) * 100.0, 1),
        "pct_underperforming_tbills": round((tbill_count / n) * 100.0, 1)
    }


def compare_distributions(
    current_stats: Dict[str, float],
    benchmark_stats: Dict[str, float],
    acceptance_bounds: Dict[str, float]
) -> Tuple[List[Dict[str, Any]], bool]:
    """Evaluates divergence against empirical benchmark and acceptance bounds."""
    checks = []
    all_passed = True

    # 1. Median Annualized ROI Bound
    med = current_stats.get("p50_median_pct", 0)
    med_min = acceptance_bounds.get("median_annualized_roi_min", 4.0)
    med_max = acceptance_bounds.get("median_annualized_roi_max", 10.0)
    med_ok = (med_min <= med <= med_max)
    if not med_ok:
        all_passed = False
    checks.append({
        "check": "Median Annualized ROI Plausibility",
        "actual": f"{med:.2f}%",
        "benchmark_large_cap": f"{benchmark_stats.get('p50_median_pct', 7.8):.2f}%",
        "acceptable_range": f"[{med_min:.1f}%, {med_max:.1f}%]",
        "status": "PASS" if med_ok else "FAIL",
        "details": "Median forward CAGR reflects realistic earnings compounding without multiple inflation."
    })

    # 2. Mean Annualized ROI Bound
    mean_v = current_stats.get("mean_pct", 0)
    mean_min = acceptance_bounds.get("mean_annualized_roi_min", 5.0)
    mean_max = acceptance_bounds.get("mean_annualized_roi_max", 12.0)
    mean_ok = (mean_min <= mean_v <= mean_max)
    if not mean_ok:
        all_passed = False
    checks.append({
        "check": "Mean Annualized ROI Plausibility",
        "actual": f"{mean_v:.2f}%",
        "benchmark_large_cap": f"{benchmark_stats.get('mean_pct', 8.9):.2f}%",
        "acceptable_range": f"[{mean_min:.1f}%, {mean_max:.1f}%]",
        "status": "PASS" if mean_ok else "FAIL",
        "details": "Mean forward CAGR aligns with historic index earnings yield + revenue trajectory."
    })

    # 3. High Compounder Rate (>=20% CAGR Hurdle)
    high_rate = current_stats.get("pct_exceeding_20_cagr", 0)
    high_min = acceptance_bounds.get("pct_exceeding_20_cagr_min", 3.0)
    high_max = acceptance_bounds.get("pct_exceeding_20_cagr_max", 20.0)
    high_ok = (high_min <= high_rate <= high_max)
    if not high_ok:
        all_passed = False
    checks.append({
        "check": "High Compounder Selectivity (>=20% CAGR)",
        "actual": f"{high_rate:.1f}%",
        "benchmark_large_cap": f"{benchmark_stats.get('pct_exceeding_20_cagr', 12.8):.1f}%",
        "acceptable_range": f"[{high_min:.1f}%, {high_max:.1f}%]",
        "status": "PASS" if high_ok else "FAIL",
        "details": "Only top high-conviction secular compounders exceed the strict 20% hurdle."
    })

    # 4. Downside / Negative Return Representation
    neg_rate = current_stats.get("pct_negative_return", 0)
    neg_max = acceptance_bounds.get("pct_negative_return_max", 35.0)
    neg_ok = (neg_rate <= neg_max)
    if not neg_ok:
        all_passed = False
    checks.append({
        "check": "Downside & Cyclical Risk Representation",
        "actual": f"{neg_rate:.1f}%",
        "benchmark_large_cap": f"{benchmark_stats.get('pct_negative_return', 21.4):.1f}%",
        "acceptable_range": f"<= {neg_max:.1f}%",
        "status": "PASS" if neg_ok else "FAIL",
        "details": "Captures cyclical multiple compression, sector headwinds, and avoid candidates."
    })

    # 5. Right-Tail Maximum Return Cap
    max_v = current_stats.get("max_pct", 0)
    max_allowed = acceptance_bounds.get("max_single_stock_cagr", 50.0)
    max_ok = (max_v <= max_allowed)
    if not max_ok:
        all_passed = False
    checks.append({
        "check": "Right-Tail Plausibility (Max 3-Year CAGR)",
        "actual": f"{max_v:.2f}%",
        "benchmark_large_cap": f"{benchmark_stats.get('max_pct', 115.0):.2f}%",
        "acceptable_range": f"<= {max_allowed:.1f}%",
        "status": "PASS" if max_ok else "FAIL",
        "details": "Prevents ungrounded 100%+ CAGR hallucinations on established large-cap equities."
    })

    # 6. Skewness Distribution Verification
    skew = current_stats.get("skewness", 0)
    skew_ok = (skew >= -3.5)
    if not skew_ok:
        all_passed = False
    checks.append({
        "check": "Distribution Symmetry & Skewness Bounds",
        "actual": f"{skew:.2f}",
        "benchmark_large_cap": f"{benchmark_stats.get('skewness', 1.15):.2f}",
        "acceptable_range": ">= -3.50 (Bounded Left/Right Tail)",
        "status": "PASS" if skew_ok else "FAIL",
        "details": "Distribution exhibits bounded tail skewness appropriate for an active hurdle-filtered equity portfolio."
    })

    return checks, all_passed


def run_comparison(root_dir: str = None) -> Dict[str, Any]:
    """Runs complete comparison workflow between current universe and empirical expected distribution."""
    if root_dir is None:
        root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    universe_path = os.path.join(root_dir, "context", "data", "universe.json")
    if not os.path.exists(universe_path):
        universe_path = os.path.join(root_dir, "http", "data", "universe.json")

    benchmark_path = os.path.join(root_dir, "context", "data", "expected_roi_distribution.json")

    if not os.path.exists(universe_path):
        raise FileNotFoundError(f"Universe data file not found at {universe_path}")
    if not os.path.exists(benchmark_path):
        raise FileNotFoundError(f"Expected ROI distribution benchmark file not found at {benchmark_path}")

    with open(universe_path, "r", encoding="utf-8") as f:
        universe = json.load(f)

    with open(benchmark_path, "r", encoding="utf-8") as f:
        bench_data = json.load(f)

    # Extract universe ROI values and ratings
    rois = []
    ratings_count = {"BUY": 0, "HOLD": 0, "SELL": 0, "AVOID": 0}
    inconsistencies = []

    for eq in universe:
        sym = eq.get("symbol", "UNKNOWN")
        status = eq.get("thesis_status", "HOLD")
        if status in ratings_count:
            ratings_count[status] += 1

        roi = eq.get("annualized_roi_pct")
        if roi is None:
            t_roi = eq.get("target_roi")
            if t_roi:
                try:
                    roi = float(str(t_roi).replace("%", ""))
                except Exception:
                    pass

        if roi is not None:
            rois.append(float(roi))

            # Sanity check rating vs ROI concordance
            if status == "BUY" and roi < 20.0:
                inconsistencies.append(f"[{sym}] Rated BUY but annualized ROI is {roi:.2f}% (< 20.0% hurdle).")
            elif status == "AVOID" and roi > 25.0:
                inconsistencies.append(f"[{sym}] Rated AVOID but annualized ROI is {roi:.2f}% (conflicting high return).")

    current_stats = compute_distribution_statistics(rois)

    # Load 3-year Large Cap Benchmark
    dist_3y = bench_data.get("distributions", {}).get("3_year_horizon", {})
    bench_large_cap = dist_3y.get("large_cap_quality_universe", {}).get("statistics", {})
    bench_broad = dist_3y.get("broad_us_equity_market", {}).get("statistics", {})
    acceptance = bench_data.get("quality_control_acceptance_criteria", {}).get("bounds", {})

    checks, all_passed = compare_distributions(current_stats, bench_large_cap, acceptance)

    if inconsistencies:
        all_passed = False

    return {
        "timestamp": "2026-08-17",
        "universe_size": len(universe),
        "evaluated_equities": len(rois),
        "ratings_breakdown": ratings_count,
        "current_universe_statistics": current_stats,
        "benchmark_large_cap_statistics": bench_large_cap,
        "benchmark_broad_market_statistics": bench_broad,
        "quality_control_checks": checks,
        "inconsistencies": inconsistencies,
        "all_passed": all_passed
    }


def print_comparison_report(res: Dict[str, Any]):
    """Outputs a clean, human-readable ASCII quality control report."""
    print("================================================================================")
    print("INVESTMENT THESIS AGENT: ANNUALIZED ROI DISTRIBUTION QUALITY CONTROL REPORT")
    print("================================================================================")
    print(f"Evaluated Universe: {res['evaluated_equities']} Equities | Benchmark: CRSP / Bessembinder & J.P. Morgan 3-Year")
    print(f"Rating Breakdown: BUY: {res['ratings_breakdown']['BUY']} | HOLD: {res['ratings_breakdown']['HOLD']} | SELL: {res['ratings_breakdown']['SELL']} | AVOID: {res['ratings_breakdown']['AVOID']}")
    print("")

    print("DISTRIBUTION PERCENTILE MATRIX COMPARISON:")
    print("+---------------+------------------+-----------------------+--------------------+")
    print("| Metric        | Current Thesis   | Large-Cap Quality     | Broad US Market    |")
    print("+---------------+------------------+-----------------------+--------------------+")
    cur = res["current_universe_statistics"]
    lc = res["benchmark_large_cap_statistics"]
    bm = res["benchmark_broad_market_statistics"]

    rows = [
        ("Min Return", f"{cur.get('min_pct',0):+.2f}%", f"{lc.get('min_pct',0):+.2f}%", f"{bm.get('min_pct',0):+.2f}%"),
        ("5th Percentile", f"{cur.get('p5_pct',0):+.2f}%", f"{lc.get('p5_pct',0):+.2f}%", f"{bm.get('p5_pct',0):+.2f}%"),
        ("10th Percentile", f"{cur.get('p10_pct',0):+.2f}%", f"{lc.get('p10_pct',0):+.2f}%", f"{bm.get('p10_pct',0):+.2f}%"),
        ("25th Percentile", f"{cur.get('p25_pct',0):+.2f}%", f"{lc.get('p25_pct',0):+.2f}%", f"{bm.get('p25_pct',0):+.2f}%"),
        ("Median (P50)", f"{cur.get('p50_median_pct',0):+.2f}%", f"{lc.get('p50_median_pct',0):+.2f}%", f"{bm.get('p50_median_pct',0):+.2f}%"),
        ("Mean", f"{cur.get('mean_pct',0):+.2f}%", f"{lc.get('mean_pct',0):+.2f}%", f"{bm.get('mean_pct',0):+.2f}%"),
        ("75th Percentile", f"{cur.get('p75_pct',0):+.2f}%", f"{lc.get('p75_pct',0):+.2f}%", f"{bm.get('p75_pct',0):+.2f}%"),
        ("90th Percentile", f"{cur.get('p90_pct',0):+.2f}%", f"{lc.get('p90_pct',0):+.2f}%", f"{bm.get('p90_pct',0):+.2f}%"),
        ("95th Percentile", f"{cur.get('p95_pct',0):+.2f}%", f"{lc.get('p95_pct',0):+.2f}%", f"{bm.get('p95_pct',0):+.2f}%"),
        ("Max Return", f"{cur.get('max_pct',0):+.2f}%", f"{lc.get('max_pct',0):+.2f}%", f"{bm.get('max_pct',0):+.2f}%"),
        ("Std Deviation", f"{cur.get('std_dev_pct',0):.2f}%", f"{lc.get('std_dev_pct',0):.2f}%", f"{bm.get('std_dev_pct',0):.2f}%"),
        ("Skewness", f"{cur.get('skewness',0):.2f}", f"{lc.get('skewness',0):.2f}", f"{bm.get('skewness',0):.2f}"),
        ("% Negative", f"{cur.get('pct_negative_return',0):.1f}%", f"{lc.get('pct_negative_return',0):.1f}%", f"{bm.get('pct_negative_return',0):.1f}%"),
        ("% >= 20% CAGR", f"{cur.get('pct_exceeding_20_cagr',0):.1f}%", f"{lc.get('pct_exceeding_20_cagr',0):.1f}%", f"{bm.get('pct_exceeding_20_cagr',0):.1f}%"),
    ]

    for label, c_val, lc_val, bm_val in rows:
        print(f"| {label:<13} | {c_val:>16} | {lc_val:>21} | {bm_val:>18} |")
    print("+---------------+------------------+-----------------------+--------------------+")
    print("")

    print("QUALITY CONTROL VERIFICATION AUDIT:")
    for chk in res["quality_control_checks"]:
        status_tag = f"[{chk['status']}]"
        print(f"{status_tag:<8} {chk['check']:<40} Actual: {chk['actual']:<8} Target: {chk['acceptable_range']}")

    if res["inconsistencies"]:
        print("\nRATING / ROI CONCORDANCE DISCREPANCIES DETECTED:")
        for inc in res["inconsistencies"]:
            print(f"[DISCREPANCY] {inc}")

    print("================================================================================")
    if res["all_passed"]:
        print("OVERALL QC STATUS: PASSED (Distribution is statistically sound and plausible)")
    else:
        print("OVERALL QC STATUS: FAILED (Divergences or anomalies detected)")
    print("================================================================================")


def main():
    parser = argparse.ArgumentParser(description="Investment Thesis ROI Distribution Quality Control Tool")
    parser.add_argument("--json", action="store_true", help="Output machine-readable JSON")
    parser.add_argument("--audit", action="store_true", help="Audit mode returning exit code 1 on failure")
    args = parser.parse_args()

    res = run_comparison()

    if args.json:
        print(json.dumps(res, indent=2))
    else:
        print_comparison_report(res)

    if args.audit and not res["all_passed"]:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
